# Generated by Django 5.0.3 on 2024-06-19 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_servicio'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
