# Generated by Django 5.0.3 on 2024-05-31 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_cliente_servicio'),
        ('api', '0006_cliente_servicio_delete_persona'),
    ]

    operations = [
    ]
